# Description: A System V Release 4.0 curses emulation library
# URL: http://www.gnu.org/software/ncurses/ncurses.html

name=ncurses
version=5.9
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --mandir=/usr/share/man \
               --with-normal \
               --with-shared \
               --without-termlib \
               --without-debug \
               --without-ada \
               --enable-sp-funcs \
	       --with-termcap

    make -j $JOBS
    make DESTDIR=$PKG install
}
