# Description: A System V Release 4.0 curses emulation library
# URL: http://www.gnu.org/software/ncurses/ncurses.html
# License: MIT

name=ncurses
version=5.9
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.gz
        http://mirror.mini-distribution.io/ncurses-5.9-patches.tar.xz)

build() {
   cd $name-$version

#   for file in $SRC/ncurses-5.9-patches/*
#   do
#      patch -p1 -i $file
#   done

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --mandir=/usr/share/man \
               --without-normal \
               --without-debug \
               --without-ada \
               --with-shared \
               --with-termlib \
               --without-profile \
               --without-ticlib \
               --without-gpm \
               --without-sysmouse \
               --disable-termcap \
               --enable-pc-files \
               --with-pkg-config-libdir=/usr/lib/pkgconfig

    make -j $JOBS
    make DESTDIR=$PKG install
}
