# Description: Access Control Lists library
# URL: http://savannah.nongnu.org/projects/acl
# License: GPLv2

name=acl
version=2.2.53
release=1
source=(http://download.savannah.gnu.org/releases/$name/$name-$version.tar.gz)
depends=attr

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
