# Description: Access Control Lists library
# URL: http://savannah.nongnu.org/projects/acl
# License: GPLv2

name=acl
version=2.2.52
release=1
source=(http://mirrors.zerg.biz/nongnu/$name/$name-$version.src.tar.gz)
depends=attr

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --libexecdir=/usr/lib

   make -j $JOBS
   make DIST_ROOT=$PKG install install-lib install-dev

   rm -r $PKG/usr/share/{doc,locale}

   # Fix libtool files
   fix_la_files $PKG
}
