# Description: Network utilities
# URL: http://sourceforge.net/projects/net-tools.berlios
# License: GPLv2

name=net-tools
version=1.60
release=1
source=(http://downloads.sourceforge.net/project/net-tools/$name-$version.tar.bz2 \
        $name-$version-config.patch \
        $name-$version-compile_fixes.patch \
        $name-$version-arp.patch \
        $name-$version-man.patch \
        $name-$version-nameif.patch \
        $name-$version-manydevs.patch \
        $name-$version-virtualname.patch \
        $name-$version-ipv6.patch \
        $name-$version-miiioctl.patch \
        $name-$version-linux-vs-netinet-include.patch)

build() {
    cd $name-$version

    patch -p1 < ../$name-$version-config.patch
    patch -p1 < ../$name-$version-compile_fixes.patch
    patch -p1 < ../$name-$version-arp.patch
    patch -p1 < ../$name-$version-man.patch
    patch -p1 < ../$name-$version-nameif.patch
    patch -p1 < ../$name-$version-manydevs.patch
    patch -p1 < ../$name-$version-virtualname.patch
    patch -p1 < ../$name-$version-ipv6.patch
    patch -p1 < ../$name-$version-miiioctl.patch
    patch -p1 < ../$name-$version-linux-vs-netinet-include.patch

    make CC="$HOST-gcc"
    make BASEDIR=$PKG/usr mandir=/share/man install
}
