# Description: The GNU troff text-formatting system
# URL: http://www.gnu.org/software/groff/groff.html
# License: GPLv3

name=groff
version=1.22.3
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.gz)

build() {
   cd $name-$version

   echo "ac_try_echo=yes" >> config.cache
   pushd src/libs/gnulib
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --cache-file=../../../config.cache
   popd
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --cache-file=config.cache

   make TROFFBIN=troff GROFFBIN=groff GROFF_BIN_PATH=
   make DESTDIR=$PKG install

   rm -rf $PKG/usr/share/{info,doc}
   ln -sf eqn $PKG/usr/bin/geqn
   ln -sf tbl $PKG/usr/bin/gtbl
   ln -sf soelim $PKG/usr/bin/zsoelim
}

check() {
   # Test for preinstalled grn tool
   check_tool grn "Can be found in the Ubuntu repos in package groff"
}
