# Description: The /proc file system utilities
# URL: http://procps.sourceforge.net/

name=procps
version=3.2.8
release=3
source=(http://procps.sourceforge.net/$name-$version.tar.gz \
        sysctl.conf \
        $name-$version.patch \
        $name-$version-linux-ver-init.patch)
depends=ncurses

build() {
   cd $name-$version
   patch -p1 -i $SRC/$name-$version.patch
   patch -p0 -i $SRC/$name-$version-linux-ver-init.patch

   make CC="$HOST-gcc"
   make DESTDIR=$PKG \
        ldconfig=true \
        bin=$PKG/usr/bin/ \
        sbin=$PKG/usr/sbin/ \
        lib=$PKG/usr/lib/ \
        man1=$PKG/usr/share/man/man1/ \
        man5=$PKG/usr/share/man/man5/ \
        man8=$PKG/usr/share/man/man8/ \
        install

   install -D -m644 ../sysctl.conf $PKG/etc/sysctl.conf
}
