# Description: System Utilities Based on Sysfs
# URL: http://linux-diag.sourceforge.net/Sysfsutils.html
# License: GPLv2 LGPLv2.1

name=sysfsutils
version=2.1.0
release=1
source=(http://downloads.sourceforge.net/project/linux-diag/$name/$version/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -f $PKG/usr/bin/dlist_test

   # Fix libtool files
   fix_la_files $PKG
}
