# Description: A unit testing framework for C
# URL: http://check.sourceforge.net
# License: LGPLv2

name=check
version=0.9.14
release=1
source=http://downloads.sourceforge.net/project/$name/$name/$version/$name-$version.tar.gz

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{doc,info}

   # Fix libtool files
   fix_la_files $PKG
}
