# Description: A unit testing framework for C
# URL: https://libcheck.github.io/check
# License: LGPLv2

name=check
version=0.12.0
release=1
source=https://github.com/libcheck/check/releases/download/$version/$name-$version.tar.gz

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{doc,info}

   # Fix libtool files
   fix_la_files $PKG
}
