# Description: A terminal based program for viewing text files
# URL: http://www.greenwoodsoftware.com/less/

name=less
version=451
release=1
source=(http://www.greenwoodsoftware.com/less/$name-$version.tar.gz \
        filter)
depends=(ncurses libpcre)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-regex=pcre

   make -j $JOBS
   make DESTDIR=$PKG install
   install -m 755 -D $SRC/filter $PKG/usr/lib/less/filter
}
