# Description: General-purpose utility library
# URL: http://developer.gnome.org/glib
# License: GPLv2

name=glib
version=2.38.2
release=1
source=(http://ftp.gnome.org/pub/gnome/sources/glib/${version%.*}/$name-$version.tar.xz)
depends=(zlib libffi dbus)

build() {
   cd $name-$version

   # Apply known hacks for cross compiling glib
   echo "glib_cv_stack_grows=yes" >> config.cache
   echo "glib_cv_uscore=no" >> config.cache
   echo "ac_cv_func_posix_getpwuid_r=yes" >> config.cache
   echo "ac_cv_func_posix_getgrgid_r=yes" >> config.cache
   echo "ac_cv_alignof_guint32=4" >> config.cache
   echo "ac_cv_alignof_guint64=8" >> config.cache
   echo "ac_cv_alignof_unsigned_long=4" >> config.cache
   echo "glib_cv_long_long_format=ll" >> config.cache
   echo "ac_cv_func_printf_unix98=yes" >> config.cache
   echo "ac_cv_func_vsnprintf_c99=yes" >> config.cache

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --cache-file=config.cache \
               --enable-debug=no \
               --disable-selinux \
               --disable-fam \
               --disable-xattr \
               --enable-man \
               --disable-Bsymbolic

   # Work around from https://bugzilla.gnome.org/show_bug.cgi?id=700350
   find  -type f -name Makefile.in -exec touch {} \;

   make -j $JOBS
   make DESTDIR=$PKG install

   # Cleanup
   rm -r $PKG/usr/share/gtk-doc
   rm -r $PKG/usr/share/locale

   # Fix libtool files
   fix_la_files $PKG
}

check() {
   # Test for preinstalled glib-genmarshal tool
   check_tool glib-genmarshal "Can be found in the Ubuntu repos in package libglib2.0-dev"
   check_tool xsltproc
   check_tool xmlcatalog "Can be found in the Ubuntu repos in package libxml2-utils"

   # Test for DocBook
   check_exist /usr/share/xml/docbook "Can be found in the Ubuntu repos in package docbook-xml"
}
