# Description: General-purpose utility library
# URL: http://developer.gnome.org/glib

name=glib
version=2.34.1
release=1
source=(http://ftp.gnome.org/pub/gnome/sources/glib/2.34/$name-$version.tar.xz)
depends=(zlib libffi dbus)

build() {
   cd $name-$version

   # Apply known hacks for cross compiling glib
   echo "glib_cv_stack_grows=yes" >> config.cache
   echo "glib_cv_uscore=no" >> config.cache
   echo "ac_cv_func_posix_getpwuid_r=yes" >> config.cache
   echo "ac_cv_func_posix_getgrgid_r=yes" >> config.cache
   echo "ac_cv_alignof_guint32=4" >> config.cache
   echo "ac_cv_alignof_guint64=8" >> config.cache
   echo "ac_cv_alignof_unsigned_long=4" >> config.cache

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --cache-file=config.cache \
               --enable-debug=no \
               --disable-selinux \
               --disable-fam \
               --disable-xattr \
               --enable-man \
               --disable-Bsymbolic

   make -j $JOBS
   make DESTDIR=$PKG install

   # Cleanup
   rm -r $PKG/usr/share/gtk-doc
   rm -r $PKG/usr/share/locale

   # Fix libtool files
   fix_la_files $PKG
}

check() {
   # Test for preinstalled glib-genmarshal tool
   check_tool glib-genmarshal
   check_tool xsltproc
   check_tool xmlcatalog

   # Test for DocBook 4.1.2
   check_lib /usr/share/xml/docbook/schema/dtd/4.1.2/catalog
}
