# Description: A general purpose cryptographic library based on GnuPG
# URL: http://www.gnupg.org
# License: GPLv3

name=libgcrypt
version=1.7.6
release=1
source=(ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-$version.tar.bz2
        0001-ac_cv_sys_symbol_underscore.patch
        0002-reconfigure.patch)
depends=libgpg-error

build() {
   cd $name-$version

   patch -p1 -i $SRC/0001-ac_cv_sys_symbol_underscore.patch
   patch -p1 -i $SRC/0002-reconfigure.patch

   GPG_ERROR_CFLAGS="-I$SYSROOT/usr/include" \
   GPG_ERROR_LIBS="-L$SYSROOT/usr/lib" \
   ac_cv_sys_symbol_underscore=no \
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --disable-padlock-support \
               --with-gpg-error-prefix=$SYSROOT/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -rf $PKG/usr/sbin
   rm -rf $PKG/usr/share/info

   # Fix libtool files
   fix_la_files $PKG
}
