# Description: Keytable files and keyboard utilities
# URL: ftp://ftp.win.tue.nl/pub/linux-local/utils/kbd/

name=kbd
version=2.0.0
release=1
source=(ftp://ftp.altlinux.org/pub/people/legion/kbd/$name-$version.tar.gz
        0001-Revert-Add-some-tests.patch)

build() {
   cd $name-$version

   patch -p1 -i $SRC/0001-Revert-Add-some-tests.patch
   autoreconf

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --datadir=/usr/share/kbd \
               --disable-nls \
               --disable-vlock
   make -j $JOBS
   make DESTDIR=$PKG install

   ln -sf default8x9.psfu.gz $PKG/usr/share/kbd/consolefonts/default.gz

   rm -r $PKG/usr/share/kbd/keymaps/{ppc,mac,atari,amiga,sun}
   rm $PKG/usr/bin/{psfxtable,mapscrn,loadunimap} \
      $PKG/usr/bin/{psfaddtable,psfgettable,psfstriptable} \
      $PKG/usr/share/man/man1/{psfaddtable.1,psfgettable.1,psfstriptable.1,psfxtable.1} \
      $PKG/usr/share/man/man8/{loadunimap.8,resizecons.8,mapscrn.8}
   find $PKG/usr/share/kbd/ -name "README*" -exec rm {} \;
}
