# Description: Application message bus system
# URL: http://www.freedesktop.org/wiki/Software/dbus
# License: AFL-2.1 GPLv2

name=dbus
version=1.8.6
release=1
source=(http://dbus.freedesktop.org/releases/dbus/$name-$version.tar.gz)
depends=(expat systemd libdbus)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --sysconfdir=/etc \
               --libexecdir=/usr/lib/dbus-1.0 \
               --localstatedir=/var \
               --with-systemdsystemunitdir=/etc/systemd/system \
               --enable-abstract-sockets \
               --with-dbus-user=root \
               --disable-tests \
               --enable-systemd

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc
   rm -r $PKG/usr/{include,lib}
   rm -r $PKG/var

   # Fix libtool files
   fix_la_files $PKG
}
