# Description: Application message bus system
# URL: http://www.freedesktop.org/wiki/Software/dbus

name=dbus
version=1.5.12
release=1
source=(http://dbus.freedesktop.org/releases/dbus/$name-$version.tar.gz)
depends=expat

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST \
               --sysconfdir=/etc \
               --libexecdir=/usr/lib/dbus-1.0 \
               --localstatedir=/var \
               --with-systemdsystemunitdir=/etc/systemd/system \
               --enable-abstract-sockets \
               --with-dbus-user=root \
               --disable-tests

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/var

   # Fix libtool files
   fix_la_files $PKG
}

