# Description: A Portable Foreign Function Interface Library 
# URL: http://sourceware.org/libffi/

name=libffi
version=3.0.11
release=1
source=(ftp://sourceware.org/pub/libffi/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/info

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $SYSROOT/usr;g" {} \;
   find $PKG -name "*.la" -exec sed -i -e "/libdir/s;'/usr;'$SYSROOT/usr;g" {} \;
}

