# Description: A Portable Foreign Function Interface Library 
# URL: http://sourceware.org/libffi
# License: MIT

name=libffi
version=3.2.1
release=1
source=(ftp://sourceware.org/pub/libffi/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/info

   # Fix libtool files
   fix_la_files $PKG
}

