# Description: XML parser
# URL: https://libexpat.github.io
# License: MIT

name=expat
version=2.2.5
release=1
source=(http://downloads.sourceforge.net/project/expat/expat/$version/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}

