# Description: XML parser
# URL: http://expat.sourceforge.net
# License: MIT

name=expat
version=2.1.0
release=1
source=(http://downloads.sourceforge.net/project/expat/expat/$version/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}

