# Description: GNU pico clone (a tiny text editor)
# URL: http://www.nano-editor.org
# License: GPLv3

name=nano
version=2.4.2
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.gz)
depends=ncurses

build(){
   cd $name-$version

   export NCURSESW_CONFIG="$SYSROOT/usr/bin/ncurses5-config"

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls \
               LDFLAGS=-ltinfo

   make -j $JOBS
   make DESTDIR=$PKG install

   rm $PKG/usr/bin/rnano $PKG/usr/share/man/man1/rnano.1
   rm -r $PKG/usr/share/info
}
