# Description: GNU pico clone (a tiny text editor)
# URL: http://www.nano-editor.org
# License: GPL-3.0+

name=nano
version=2.2.6
release=1
source=(http://www.nano-editor.org/dist/v2.2/$name-$version.tar.gz)
depends=ncurses

build(){
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls \
               LDFLAGS=-ltinfo

   make -j $JOBS
   make DESTDIR=$PKG install

   rm $PKG/usr/bin/rnano $PKG/usr/share/man/man1/rnano.1
   rm -r $PKG/usr/share/info
}
