# Description: Iproute2 is a collection of utilities for controlling TCP / IP networking and traffic control in Linux.
# URL: http://www.linuxfoundation.org/collaborate/workgroups/networking/iproute2
# License: GPLv2

name=iproute2
version=4.13.0
release=1
source=(https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-$version.tar.xz)
depends=(iptables native/linux-source)

build() {
   cd $name-$version

   # Remove dependency on Berkeley DB
   sed -i '/^TARGETS/s@arpd@@g' misc/Makefile
   sed -i '/ARPD/d' Makefile
   sed -i 's/arpd.8//' man/man8/Makefile

   make -j$JOBS HOSTCC=gcc CC=$HOST-gcc KERNEL_INCLUDE=$NATIVE_SYSROOT/usr/src/linux
   make DESTDIR=$PKG SBINDIR=/usr/sbin install

   # Clean up doc
   rm -rf $PKG/usr/share/doc
}
