# Description: Library giving userland programs access to USB devices
# URL: http://libusb.org
# License: LGPLv2.1

name=libusb
version=1.0.18
release=1
source=(http://downloads.sourceforge.net/libusbx/libusbx-$version.tar.bz2)
depends=systemd

build () {
   cd libusbx-$version
  
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
