# Description: GNU grep, egrep and fgrep
# URL: http://www.gnu.org/software/grep/grep.html
# License: GPLv3

name=grep
version=2.25
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.xz)
depends=libpcre

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/info
}
