# Description: Miscellaneous system utilities
# URL: http://kernel.org/~kzak/util-linux
# License: GPL-2.0+ LGPL-2.0+ BSD PD

name=util-linux
version=2.23.2
release=1
source=(http://www.kernel.org/pub/linux/utils/util-linux/v${version%.*}/$name-$version.tar.xz)
depends=(ncurses zlib)

build() {

   cd $name-$version

   echo "scanf_cv_alloc_modifier=ms" > config.cache

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --exec-prefix=/usr \
               --bindir=/usr/bin \
               --sbindir=/usr/sbin \
               --libdir=/usr/lib \
               --disable-{nls,elvtune,wall,fallocate,login,su} \
               --enable-{write,raw,kill} \
               --cache-file=config.cache \
               LDFLAGS=-ltinfo

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -rf $PKG/usr/share/man/ru
  
   # Fix libtool files
   fix_la_files $PKG
}
