# Description: System and service manager for Linux
# URL: http://www.freedesktop.org/wiki/Software/systemd
# License: LGPL-2.1+, MIT, PD, GPL-2.0+

name=systemd
version=207
release=1
source=(http://www.freedesktop.org/software/systemd/$name-$version.tar.xz
        systemd-disable-pager.patch
        systemd-journalctl-enable-all-option.patch
        systemd-journal-disable-FS_NOCOW_FL-attr.patch
        vconsole.conf)
depends=(libcap dbus kmod util-linux pciutils glib tcp_wrappers libgcrypt)

build() {
   cd $name-$version

   patch -p1 < $SRC/systemd-disable-pager.patch
   patch -p1 < $SRC/systemd-journalctl-enable-all-option.patch
   patch -p1 < $SRC/systemd-journal-disable-FS_NOCOW_FL-attr.patch

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --sysconfdir=/etc \
               --libexecdir=/usr/lib \
               --localstatedir=/var \
               --disable-nls \
               --without-python \
               --with-firmware-path=/lib/firmware \
               ac_cv_func_malloc_0_nonnull=yes

   make -j $JOBS \
        GCRYPT_LIBS="-lgcrypt" \
        LIBGCRYPT_LIBS="-lgcrypt"

   make DESTDIR=$PKG install \
        GCRYPT_LIBS="-lgcrypt" \
        LIBGCRYPT_LIBS="-lgcrypt"

   # Systemd required fixes
   ln -s /proc/self/mounts $PKG/etc/mtab
   install -d $PKG/usr/sbin
   ln -s /usr/lib/systemd/systemd $PKG/usr/sbin/init
   install -Dm644 $SRC/vconsole.conf $PKG/etc/vconsole.conf

   # Initialize network before making getty login available on serial
   sed -i "/After=/s|$| network.target|" $PKG/usr/lib/systemd/system/serial-getty@.service

   # Boot into multi-user target (non-graphical)
   ln -sf multi-user.target $PKG/usr/lib/systemd/system/default.target

   # Cleanup
   rm $PKG/usr/lib/tmpfiles.d/legacy.conf
   rm $PKG/usr/lib/tmpfiles.d/x11.conf
   rm $PKG/usr/lib/udev/rules.d/73-seat-late.rules

   # Fix libtool files
   fix_la_files $PKG
}

check() {
   # Test for preinstalled intltool-update tool
   check_tool intltool-update "Please install intltool"
   check_exist /usr/share/xml/docbook/stylesheet/docbook-xsl "Please install docbook-xsl"
}
