# Description: System and service manager for Linux
# URL: http://www.freedesktop.org/wiki/Software/systemd

name=systemd
version=193
release=1
source=(http://www.freedesktop.org/software/systemd/$name-$version.tar.xz
        vconsole.conf)
depends=(libcap dbus kmod util-linux usbutils pciutils glib tcp_wrappers python libgcrypt)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --sysconfdir=/etc \
               --libexecdir=/usr/lib \
               --localstatedir=/var \
               --with-distro=other \
               --with-usb-ids-path=/usr/lib/usb.ids \
               --with-pci-ids-path=/usr/share/pci.ids \
               --disable-nls

   make -j $JOBS \
        GCRYPT_LIBS="-lgcrypt" \
        LIBGCRYPT_LIBS="-lgcrypt" \
        PYTHON_CFLAGS=`pkg-config python --cflags` \
        PYTHON_LIBS=`pkg-config python --libs`

   # Fix libtool paths
   find . -name "*.la" -exec sed -i -e "/libdir/s;'/usr;'$SYSROOT/usr;g" {} \;

   # Disable libtool relinking (relinking of rpaths b/c of DESTDIR install relocation)
   sed -i "s|need_relink=yes|need_relink=no|" libtool

   make DESTDIR=$PKG install \
        GCRYPT_LIBS="-lgcrypt" \
        LIBGCRYPT_LIBS="-lgcrypt"

   # Systemd required fixes
   ln -s /proc/self/mounts $PKG/etc/mtab
   install -d $PKG/usr/sbin
   ln -s /usr/lib/systemd/systemd $PKG/usr/sbin/init
   install -Dm644 $SRC/vconsole.conf $PKG/etc/vconsole.conf

   # Initialize network before making getty login available on serial
   sed -i "/After=/s|$| network.target|" $PKG/usr/lib/systemd/system/serial-getty@.service

   # Boot into multi-user target (non-graphical)
   ln -sf multi-user.target $PKG/usr/lib/systemd/system/default.target

   # Cleanup
   rm $PKG/usr/lib/tmpfiles.d/legacy.conf
   rm $PKG/usr/lib/tmpfiles.d/x11.conf
   rm $PKG/usr/lib/udev/rules.d/73-seat-late.rules

   # Fix libtool files
   fix_la_files $PKG
}

check() {
   # Test for preinstalled intltool-update tool
   check_tool intltool-update
}
