# Description: System and service manager for Linux
# URL: http://www.freedesktop.org/wiki/Software/systemd

name=systemd
version=185
release=1
source=(http://www.freedesktop.org/software/systemd/$name-$version.tar.xz
        vconsole.conf)
depends=(libcap dbus kmod util-linux usbutils pciutils glib)

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST \
               --sysconfdir=/etc \
               --libexecdir=/usr/lib \
               --localstatedir=/var \
               --with-distro=other \
               --enable-split-usr \
               --with-usb-ids-path=/usr/lib/usb.ids \
               --with-pci-ids-path=/usr/share/pci.ids \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install

   # Systemd required configuration
   ln -s /proc/self/mounts $PKG/etc/mtab
   mkdir $PKG/usr/sbin
   ln -s /usr/lib/systemd/systemd $PKG/usr/sbin/init
   install -Dm644 $SRC/vconsole.conf $PKG/etc/vconsole.conf

   # Cleanup
   rm $PKG/usr/lib/tmpfiles.d/legacy.conf
   rm $PKG/usr/lib/tmpfiles.d/x11.conf

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $SYSROOT/usr;g" {} \;
   find $PKG -name "*.la" -exec sed -i -e "/libdir/s;'/usr;'$SYSROOT/usr;g" {} \;
}

check() {
   # Test for preinstalled intltool-update tool
   type intltool-update
}
