# Description: pciutils-like utilities for USB
# URL:  https://github.com/gregkh/usbutils
# License: GPLv2

name=usbutils
version=007
release=1
source=(https://www.kernel.org/pub/linux/utils/usb/$name/$name-$version.tar.xz)
depends=libusb

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-zlib \
               --datarootdir=/usr/lib \
               --mandir=/usr/share/man
   
   make -j $JOBS
   make DESTDIR=$PKG install
}
