# Description: pciutils-like utilities for USB
# URL:  https://github.com/gregkh/usbutils

name=usbutils
version=005
release=1
source=(http://crux.s3.amazonaws.com/dist/$name-$version.tar.xz)
depends=(cross/libusb)

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST \
	       --disable-zlib \
	       --datarootdir=/usr/lib \
	       --mandir=/usr/share/man
   
   make -j $JOBS
   make DESTDIR=$PKG install
}
