# Description: Secure Sockets Layer and Transport Layer Security tools
# URL: http://www.openssl.org
# License: OpenSSL

name=openssl
version=1.0.1g
release=1
source=(http://www.openssl.org/source/$name-$version.tar.gz
	openssl-1.0.1-parallel-build.patch pod2man.patch)
depends=zlib

build() {
   cd $name-$version

   patch -p1 < $SRC/openssl-1.0.1-parallel-build.patch

   ./Configure --prefix=/usr \
               --cross-compile-prefix=$HOST- \
               --install_prefix=$PKG \
               --openssldir=/etc/ssl \
               no-krb5 \
               zlib-dynamic \
               threads \
               shared \
               linux-generic32

  patch -p1 < $SRC/pod2man.patch

  make -j $JOBS
  make MANDIR=/usr/share/man MANSUFFIX=ssl install
}
