# Description: Secure Sockets Layer and Transport Layer Security tools
# URL: http://www.openssl.org
# License: OpenSSL

name=openssl
version=1.0.2n
release=1
source=(https://ftp.openssl.org/source/old/1.0.2/openssl-$version.tar.gz
        pod2man.patch)
depends=zlib

build() {
   cd $name-$version

   ./Configure --prefix=/usr \
               --cross-compile-prefix=$HOST- \
               --install_prefix=$PKG \
               --openssldir=/etc/ssl \
               no-krb5 \
               zlib-dynamic \
               threads \
               shared \
               linux-generic32

   patch -p1 < $SRC/pod2man.patch

   make -j $JOBS
   make MANDIR=/usr/share/man MANSUFFIX=ssl install
}
