# Description: Library and utilities to access the PCI bus configuration registers
# URL: http://mj.ucw.cz/pciutils.shtml
# License: GPLv2

name=pciutils
version=3.4.1
release=1
source=(http://www.kernel.org/pub/software/utils/$name/$name-$version.tar.xz)

build() {
   cd $name-$version

   make -j $JOBS \
        CC="$HOST-gcc" \
        AR="$HOST-ar" \
        RANLIB="$HOST-ranlib" \
        PREFIX=/usr \
        ZLIB=no \
        SHARED=yes

   make DESTDIR=$PKG \
        PREFIX=/usr \
        MANDIR=/usr/share/man \
        STRIP="" \
        install install-lib
}
