# Description: Library for managing Linux capabilities
# URL: https://sites.google.com/site/fullycapable
# License: BSD GPLv2

name=libcap
version=2.25
release=1
source=(https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/$name-$version.tar.xz
        0001-Fix-build-with-gperf-3.1.patch)
depends=attr

build() {
   cd $name-$version

   patch -p1 -i $SRC/0001-Fix-build-with-gperf-3.1.patch

   make -j $JOBS \
         BUILD_CC=gcc \
         CC=$HOST-gcc \
         AR=$HOST-ar \
         RANLIB=$HOST-ranlib \
         PAM_CAP=no

   make -C libcap \
         DESTDIR=$PKG \
         lib=usr/lib \
         install

   rm $PKG/usr/lib/libcap.a
}
