# Description: Library for managing Linux capabilities
# URL: https://sites.google.com/site/fullycapable

name=libcap
version=2.22
release=1
source=(http://mirror.linux.org.au/linux/libs/security/linux-privs/libcap2/$name-$version.tar.bz2)
depends=attr

build() {
   cd $name-$version

   make -j $JOBS CC=$HOST-gcc AR=$HOST-ar RANLIB=$HOST-ranlib BUILD_CC=gcc
   make -C libcap DESTDIR=$PKG lib=usr/lib install
}

