# Description: A network utility for downloading content from the Web
# URL: http://www.gnu.org/software/wget/

name=wget
version=1.13
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.xz \
        wgetrc)
depends=openssl

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --sysconfdir=/etc \
               --with-ssl=openssl \
               --disable-debug \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install
   install -D -m 0644 $SRC/wgetrc $PKG/etc/wgetrc

   rm -r $PKG/usr/share/info
}
