# Description: Small utilities that use the /proc filesystem
# URL: http://psmisc.sourceforge.net/
# License: BSD, GPL-2.0

name=psmisc
version=22.20
release=1
source=(http://heanet.dl.sourceforge.net/project/psmisc/psmisc/$name-$version.tar.gz)
depends=ncurses

build() {
   cd $name-$version

   echo "ac_cv_func_malloc_0_nonnull=yes" >> config.cache
   echo "ac_cv_func_realloc_0_nonnull=yes" >> config.cache

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls \
               --cache-file=config.cache
  
   make -j $JOBS
   make DESTDIR=$PKG install

   rm -f $PKG/usr/bin/pstree.x11
}
