# Description: Commands for Manipulating Filesystem Extended Attributes
# URL: http://savannah.nongnu.org/projects/attr

name=attr
version=2.4.46
release=1
source=(http://mirrors.zerg.biz/nongnu/attr/$name-$version.src.tar.gz)

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST
   make -j $JOBS
   make DIST_ROOT=$PKG install install-lib install-dev

   # Fix libtool files
   fix_la_files $PKG
}

check() {
   # Test for preinstalled msgfmt tool
   check_tool msgfmt
}
