# Description: Commands for Manipulating Filesystem Extended Attributes
# URL: http://savannah.nongnu.org/projects/attr

name=attr
version=2.4.46
release=1
source=(http://mirrors.zerg.biz/nongnu/attr/$name-$version.src.tar.gz)

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST
   make -j $JOBS
   make DIST_ROOT=$PKG install install-lib install-dev

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $SYSROOT/usr;g" {} \;
   find $PKG -name "*.la" -exec sed -i -e "/libdir/s;'/usr;'$SYSROOT/usr;g" {} \;
}

check() {
   # Test for preinstalled msgfmt tool
   type msgfmt
}
