# Description: Commands for Manipulating Filesystem Extended Attributes
# URL: http://savannah.nongnu.org/projects/attr
# License: GPLv2

name=attr
version=2.4.47
release=1
source=(http://mirrors.zerg.biz/nongnu/attr/$name-$version.src.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --disable-nls

   make -j $JOBS
   make DIST_ROOT=$PKG install install-lib install-dev

   rm -rf $PKG/usr/share/{doc,locale}

   # Fix libtool files
   fix_la_files $PKG
}

check() {
   # Test for preinstalled msgfmt tool
   check_tool msgfmt "Please install msgfmt"
}
