# Description: Perl Compatible Regular Expressions
# URL: http://www.pcre.org
# License: BSD

name=libpcre
version=8.35
release=1
source=(ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-$version.tar.bz2)

build() {
   cd pcre-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --enable-utf8 \
               --enable-unicode-properties \
               --enable-pcre{16,32}

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
