# Description: The proc file system utilities
# URL: http://procps-ng.sourceforge.net
# License: GPLv2 LGPLv2

name=procps-ng
version=3.3.12
release=1
source=(http://downloads.sourceforge.net/project/procps-ng/Production/$name-$version.tar.xz \
        99-sysctl.conf)
depends=(ncurses systemd)

build() {
   cd $name-$version

   export LIBS=-ltinfo

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls \
               --disable-static \
               --exec-prefix=/ \
               --sysconfdir=/etc \
               --libdir=/usr/lib \
               --bindir=/usr/bin \
               --sbindir=/usr/sbin \
               --with-ncurses \
               --with-systemd \
               ac_cv_func_malloc_0_nonnull=yes \
               ac_cv_func_realloc_0_nonnull=yes

   make -j $JOBS
   make DESTDIR=$PKG install

   install -D -m644 $SRC/99-sysctl.conf $PKG/etc/sysctl.d/99-sysctl.conf

   rm -rf $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
