# Description: Filesystem skeleton
# URL: http://www.buildgear.io

name=fs-skeleton
version=1.0
release=1
source=(group ld.so.conf)

build() {

   # Create basic directories
   install -d $PKG/home
   install -d $PKG/root
   install -d $PKG/usr
   install -d $PKG/etc
   install -d $PKG/dev
   install -d $PKG/proc
   install -d $PKG/sys
   install -d $PKG/tmp
   install -d $PKG/media
   install -d $PKG/mnt
   install -d $PKG/lib
   install -d $PKG/srv
   install -d $PKG/opt
   install -d $PKG/var
   install -d $PKG/run

   # Create symlinks
   ln -s usr/bin $PKG/bin
   ln -s usr/sbin $PKG/sbin
   ln -s ../var $PKG/usr/var
   ln -s ../run $PKG/var/run

   # Create users with SHA512 password
   echo "root:x:0:0:root:/root:/bin/bash" >> $PKG/etc/passwd
   echo -e "root:\$6\$01010101\$9M5Kunmy0spJHC.1Zp7RMMYMGXAJJllD.4cFpMlJEDtySqkf.TLNN4sRZ/u4oloRFcHrDJvYV5xYhJwgGZvc/1:16375:0:99999:7:::" >> $PKG/etc/shadow

   # Create dynamic linker configuration
   install -d $PKG/etc/ld.so.conf.d
   cp $SRC/ld.so.conf $PKG/etc
}
