# Description: Filesystem skeleton
# URL: http://www.buildgear.org

name=fs-skeleton
version=1.0
release=1
source=(group ld.so.conf)

build() {
   # Create basic directories
   mkdir -p $PKG/home
   mkdir -p $PKG/root
   mkdir -p $PKG/usr
   mkdir -p $PKG/etc
   mkdir -p $PKG/dev
   mkdir -p $PKG/proc
   mkdir -p $PKG/sys
   mkdir -p $PKG/tmp
   mkdir -p $PKG/media
   mkdir -p $PKG/mnt
   mkdir -p $PKG/lib
   mkdir -p $PKG/srv
   mkdir -p $PKG/opt
   mkdir -p $PKG/var
   mkdir -p $PKG/run

   # Create symlinks
   ln -s /usr/bin $PKG/bin
   ln -s /usr/sbin $PKG/sbin
   ln -s ../var $PKG/usr/var
   ln -s ../run $PKG/var/run

   # Create users
   echo "root:it3Y6aTzjxuyE:0:0:root:/root:/bin/bash" >> $PKG/etc/passwd

   # Create groups
   cp $SRC/group $PKG/etc/group

   # Create dynamic linker configuration
   mkdir -p $PKG/etc/ld.so.conf.d
   cp $SRC/ld.so.conf $PKG/etc
}
