# Description: A pattern scanning and processing language
# URL: http://www.gnu.org/software/gawk/gawk.html
# License: GPLv3+

name=gawk
version=4.1.0
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.xz
        disable-shared-check.patch)

build() {
   cd $name-$version

   patch -p2 < $SRC/disable-shared-check.patch

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --libexecdir=/usr/lib \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/info
}
