# Description: Application message bus system
# URL: http://www.freedesktop.org/wiki/Software/dbus
# License: AFL-2.1 GPLv2

name=libdbus
version=1.8.12
release=1
source=(http://dbus.freedesktop.org/releases/dbus/dbus-$version.tar.gz)
depends=(expat)

build() {
   cd dbus-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --sysconfdir=/etc \
               --libexecdir=/usr/lib/dbus-1.0 \
               --localstatedir=/var \
               --enable-abstract-sockets \
               --with-dbus-user=root \
               --disable-tests \
               --disable-systemd

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/etc
   rm -r $PKG/usr/bin
   rm -r $PKG/usr/share
   rm -r $PKG/var

   # Fix libtool files
   fix_la_files $PKG
}
