# Description: Basic file, shell and text manipulation utilities
# URL: http://www.gnu.org/software/coreutils
# License: GPLv3

name=coreutils
version=8.22
release=1
source=(http://ftp.gnu.org/gnu/coreutils/$name-$version.tar.xz
        coreutils-8.22-noman-1.patch
        coreutils-8.22-uname-1.patch)
depends=(libcap attr acl gmp)

build() {
   cd $name-$version

   patch -p1 < $SRC/coreutils-8.22-noman-1.patch
   patch -p1 < $SRC/coreutils-8.22-uname-1.patch

   echo "fu_cv_sys_stat_statfs2_bsize=yes" >> config.cache
   echo "gl_cv_func_working_mkstemp=yes" >> config.cache
   echo "ac_cv_func_canonicalize_file_name=no" >> config.cache
   echo "gl_cv_func_working_acl_get_file=yes" >> config.cache

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --libexecdir=/usr/lib \
               --disable-nls \
               --disable-assert \
               --with-gmp \
               --cache-file=config.cache

   make -j $JOBS

   make DESTDIR=$PKG install

   rm -r $PKG/usr/share
}

