# Description: Basic file, shell and text manipulation utilities
# URL: http://www.gnu.org/software/coreutils
# License: GPLv3

name=coreutils
version=8.27
release=1
source=(http://ftp.gnu.org/gnu/coreutils/$name-$version.tar.xz
        003_all_coreutils-uname.patch
        030_all_coreutils-more-dir-colors.patch
        040_all_coreutils-cp-mkdir-eexist.patch
        coreutils-8.25-enable-ls-colors-for-vt102.patch
        man-decouple-manpages-from-build.patch
        0001-local.mk-fix-cross-compiling-problem.patch)
depends=(libcap attr acl gmp)

build() {
   cd $name-$version

   for file in $SRC/*.patch
   do
      patch -p1 -i $file
   done

   echo "fu_cv_sys_stat_statfs2_bsize=yes" >> config.cache
   echo "gl_cv_func_working_mkstemp=yes" >> config.cache
   echo "ac_cv_func_canonicalize_file_name=no" >> config.cache
   echo "gl_cv_func_working_acl_get_file=yes" >> config.cache

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --libexecdir=/usr/lib \
               --disable-nls \
               --disable-assert \
               --with-gmp \
               --cache-file=config.cache

   make -j $JOBS

   make DESTDIR=$PKG install

   # Cleanup
   rm -r $PKG/usr/share
}

