# Description: Free library for arbitrary precision arithmetic
# URL: http://gmplib.org
# License: LGPLv3

name=gmp
version=6.0.0a
release=1
source=(ftp://ftp.gnu.org/gnu/$name/$name-$version.tar.xz)

build() {
   cd $name-6.0.0

   CC_FOR_BUILD=cc \
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --enable-cxx \
               --without-readline

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share

   # Fix libtool files
   fix_la_files $PKG
}
