# Description: GNU Tar
# URL: http://www.gnu.org/software/tar/
# License: GPL

name=tar
version=1.28
release=1
source=(http://ftp.gnu.org/gnu/tar/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
