# Description: GNU compression utility
# URL: http://www.gzip.org
# License: GPLv2

name=gzip
version=1.6
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/info
}
