# Description: An sh-compatible command language interpreter
# URL: http://cnswww.cns.cwru.edu/~chet/bash/bashtop.html
# License: GPLv3

name=bash
version=4.3
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.gz profile
        http://buildgear.org/mirror/bash-4.3-patches-30.tar.xz)
depends=ncurses

build() {
   cd $name-$version

   for file in $SRC/bash-$version-patches-*/*
   do
      patch -p0 -i $file
   done

   echo "bash_cv_sys_named_pipes=yes" >> config.cache
   echo "bash_cv_job_control_missing=present" >> config.cache

   touch configure
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --cache-file=config.cache \
               --exec-prefix=/usr \
               --disable-nls \
               --without-bash-malloc \
               --with-curses

   make -j $JOBS
   make DESTDIR=$PKG install

   install -D -m 644 $SRC/profile $PKG/etc/profile
   install -d $PKG/etc/profile.d

   # Make bash default shell
   ln -s bash $PKG/usr/bin/sh
   ln -s bash.1 $PKG/usr/share/man/man1/sh.1

   rm -r $PKG/usr/share/{info,doc}
}
