# Description: The Linux System V Init tools
# URL: ftp://ftp.cistron.nl/pub/people/miquels/sysvinit/
# License: GPLv2+

name=sysvinit
version=2.88
release=1
source=(http://mirror3.layerjet.com/nongnu/$name/$name-${version}dsf.tar.bz2)

build() {
   cd $name-${version}dsf

   make -C src CC="$HOST-gcc" SULOGINLIBS="-lcrypt"
   make -C src ROOT=$PKG install

   mkdir $PKG/usr/sbin
   mv $PKG/bin/* $PKG/usr/bin
   mv $PKG/sbin/* $PKG/usr/sbin

   rmdir $PKG/{bin,sbin}
   rm $PKG/usr/sbin/init
}
