# Description: OpenSSH SSH client and server
# URL: http://www.openssh.org
# License: BSD

name=openssh
version=7.1p2
release=1
source=(http://www.mirrorservice.org/pub/OpenBSD/OpenSSH/portable/$name-$version.tar.gz
        sshdgenkeys.service
        sshd@.service
        sshd.socket)
depends=(zlib openssl)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --sysconfdir=/etc/ssh \
               --disable-strip \
               --with-privsep-user=root \
               --disable-nls

   install -Dm644 $SRC/sshdgenkeys.service $PKG/etc/systemd/system/sshdgenkeys.service
   install -Dm644 $SRC/sshd@.service $PKG/etc/systemd/system/sshd@.service
   install -Dm644 $SRC/sshd.socket $PKG/etc/systemd/system/sshd.socket

   make -j $JOBS
   make DESTDIR=$PKG install
}
