# Description: Library to deal with kernel modules
# URL: http://git.profusion.mobi/cgit.cgi/kmod.git

name=kmod
version=10
release=1
source=(http://www.kernel.org/pub/linux/utils/kernel/kmod/$name-$version.tar.xz)

build(){
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install

   ln -s /usr/bin/kmod $PKG/usr/bin/lsmod
   ln -s /usr/bin/kmod $PKG/usr/bin/rmmod
   ln -s /usr/bin/kmod $PKG/usr/bin/insmod
   ln -s /usr/bin/kmod $PKG/usr/bin/modinfo
   ln -s /usr/bin/kmod $PKG/usr/bin/modprobe
   ln -s /usr/bin/kmod $PKG/usr/bin/depmod

   # Fix libtool files
   fix_la_files $PKG
}
