# Description: Library to deal with kernel modules
# URL: http://git.profusion.mobi/cgit.cgi/kmod.git

name=kmod
version=8
release=1
source=(http://www.kernel.org/pub/linux/utils/kernel/kmod/$name-$version.tar.xz)

build(){
   cd $name-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install

   ln -s /usr/bin/kmod $PKG/usr/bin/lsmod
   ln -s /usr/bin/kmod $PKG/usr/bin/rmmod
   ln -s /usr/bin/kmod $PKG/usr/bin/insmod
   ln -s /usr/bin/kmod $PKG/usr/bin/modinfo
   ln -s /usr/bin/kmod $PKG/usr/bin/modprobe
   ln -s /usr/bin/kmod $PKG/usr/bin/depmod

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $SYSROOT/usr;g" {} \;
   find $PKG -name "*.la" -exec sed -i -e "/libdir/s;'/usr;'$SYSROOT/usr;g" {} \;
}
