# Description: A compression/decompression Library
# URL: http://www.zlib.net

name=zlib
version=1.2.7
release=1
source=http://www.zlib.net/$name-$version.tar.bz2

build() {
   cd $name-$version

   CROSS_PREFIX=$HOST- \
   ./configure --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
