# Description: Shadow password file utilities
# URL: http://pkg-shadow.alioth.debian.org
# License: BSD

name=shadow
version=4.2.1
release=1
source=(http://mirror.mini-distribution.io/$name-$version.tar.xz \
        shadow-4.2.1-subids-fix.patch \
        shadow.timer shadow.service \
        login.defs)

build() {
   cd $name-$version

   patch -p1 -i $SRC/shadow-4.2.1-subids-fix.patch

   # Don't set suid on installed binaries
   sed -i 's/\(^suidu*bins = \).*/\1/' src/Makefile.in

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --bindir=/usr/bin \
               --sbindir=/usr/sbin \
               --libdir=/usr/lib \
               --mandir=/usr/share/man \
               --sysconfdir=/etc \
               --disable-shared \
               --disable-nls \
               --without-selinux \
               --without-libpam \
               --disable-subordinate-ids \
               --disable-shadowgrp \
               --without-audit \
               --without-acl \
               --without-attr \
               --without-tcb \
               --with-group-name-max-length=32

   make -j $JOBS
   make DESTDIR=$PKG install

   # Install and enable systemd timer to trigger shadow integrity checks
   install -D -m644 $SRC/shadow.timer $PKG/usr/lib/systemd/system/shadow.timer
   install -D -m644 $SRC/shadow.service $PKG/usr/lib/systemd/system/shadow.service
   install -d -m755 $PKG/usr/lib/systemd/system/multi-user.target.wants
   ln -s ../shadow.timer $PKG/usr/lib/systemd/system/multi-user.target.wants/shadow.timer

   # Install login configuration
   install -m 644 $SRC/login.defs $PKG/etc

   install -d $PKG/var/log
   touch $PKG/var/log/{lastlog,faillog}

   # Remove broken tools
   rm $PKG/usr/sbin/logoutd

   # Remove utilities better provided by coreutils
   rm $PKG/usr/bin/groups
   rm $PKG/usr/share/man/man1/groups.1

   # Remove utilities better provided by util-linux
   rm $PKG/usr/sbin/nologin
   rm $PKG/usr/share/man/man8/nologin.8
}
