# Description: Shadow password file utilities
# URL: http://pkg-shadow.alioth.debian.org/

name=shadow
version=4.1.5.1
release=1
source=(http://pkg-shadow.alioth.debian.org/releases/$name-$version.tar.bz2 \
        pwck login.defs)

build() {
  cd $name-$version

  echo "ac_cv_func_setpgrp_void=yes" >> config.cache

  ./configure --build=$BUILD \
              --host=$HOST \
              --prefix=/usr \
              --bindir=/usr/bin \
              --sbindir=/usr/sbin \
              --sysconfdir=/etc \
              --disable-shared \
              --disable-shadowgrp \
              --disable-nls \
              --without-selinux \
              --without-libpam \
              --without-audit \
              --cache-file=config.cache

  make
  make DESTDIR=$PKG install

  install -d $PKG/etc/cron/daily $PKG/var/log
  install -m 644 $SRC/login.defs $PKG/etc
  install -m 755 $SRC/pwck $PKG/etc/cron/daily
  touch $PKG/var/log/{lastlog,faillog}

  rm -r $PKG/usr/bin/gpasswd \
        $PKG/usr/share/man/man1/gpasswd.1 \
        $PKG/usr/sbin/{chpasswd,grpconv,grpunconv,logoutd} \
        $PKG/usr/sbin/{newusers,pwconv,pwunconv} \
        $PKG/usr/share/man/man8/{chpasswd.8,grpconv.8,grpunconv.8,logoutd.8} \
        $PKG/usr/share/man/man8/{newusers.8,pwconv.8,pwunconv.8} \
        $PKG/usr/share/man/man5/gshadow.5 \
        $PKG/usr/share/man/man3 \
        $PKG/etc/{login.access,limits,default}
}
