# Description: Basic networking applet
# URL: http://www.linuxfoundation.org/collaborate/workgroups/networking/iputils
# License: BSD GPLv2 Rdisc

name=iputils
version=s20151218
release=1
source=(http://www.skbuff.net/iputils/$name-$version.tar.bz2
        http://crux.nu/files/distfiles/$name-man-$version.tar.xz)
depends=(sysfsutils libcap openssl libgcrypt)

build() {
   cd $name-$version

   make -j $JOBS CC="$HOST-gcc" USE_GNUTLS=no

   install -d $PKG/usr/share/man/man8
   install -d $PKG/usr/{bin,sbin}
   install ping{,6} $PKG/usr/bin
   install arping $PKG/usr/sbin
   install tracepath{,6} traceroute6 clockdiff rarpd rdisc ipg $PKG/usr/sbin
   cp -d $SRC/$name-man-$version/* $PKG/usr/share/man/man8
   chmod u+s $PKG/usr/bin/ping{,6} $PKG/usr/sbin/traceroute6

   rm $PKG/usr/share/man/man8/*6.*
}
